name: Build Data Broker (Win + Linux)

on:
  push:
  pull_request:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build (release)
        run: cargo build --release

      # --- ZIP упаковка для Linux ---
      - name: Create ZIP (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd target/release
          zip data_broker_linux.zip data_broker

      # --- ZIP упаковка для Windows ---
      - name: Create ZIP (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cd target\release
          powershell Compress-Archive -Path data_broker.exe -DestinationPath data_broker_windows.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: data-broker-${{ matrix.os }}
          path: |
            target/release/*.zip
